coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "core"
          - "website"
          - "slurm"
        # advanced
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false